name: tobischw.me
description: I'm a CS student with a passion for AI, web dev, and everything in between.
author: Tobi Schweiger
theme: jekyll-theme-minimal
title: tobischw.me
show_downloads: false
logo: static/img/me.png